### ISSUE TITLE
Container restart policy

### ISSUE THREAD

**Issue by ejr004** [simple-framework/simple_htcondor_ce#15]
Shall we give the option to set the restart policy of the container ?

docker run -dit --restart unless-stopped $(docker ps -qa)

**Comment by maany** [comment]
- [ ] Create a init service for init.sh
- [ ]  Enable the service at the end of init.sh
- [ ] The service itself runs init.sh

**Comment by maany** [comment]
At present we just enable all the daemons like condor-ce, condor, cron, ... as all the config is already present in the containers in their stopped state
